# ---------------------------------------------------------------------------- #
# Task configs
# ---------------------------------------------------------------------------- #
epochs: 300
mode: train                   # [train, test]
grad_norm_clip: 1
# seed: 6

# ---------------------------------------------------------------------------- #
# Experimenet configs
# ---------------------------------------------------------------------------- #
experiment:
  exp_root_path: ../output

# ---------------------------------------------------------------------------- #
# Dataset configs
# ---------------------------------------------------------------------------- #
dataset:
  common:
    NAME: ScanObjectNN
    data_path: ../data/ScanObjectNN
    num_points: 1024
  train:
    split: train
  test:
    split: test

# ---------------------------------------------------------------------------- #
# Dataloader configs
# ---------------------------------------------------------------------------- #
dataloader:
  train:
    batch_size: 32
  test:
    batch_size: 16

# ---------------------------------------------------------------------------- #
# Model configs
# ---------------------------------------------------------------------------- #
model:
  NAME: PointNetV11
  n_cls: 15
  d_in: 3
  d_stem: 32
  d_feats: [64, 128, 256, 512]
  g_ns: [1024, 256, 64, 16]
  g_ks: [32, 32, 32, 16]
  g_rs: [0.2, 0.4, 0.8, 1.6]
  norm: BN
  act: ReLU

# ---------------------------------------------------------------------------- #
# Loss configs
# ---------------------------------------------------------------------------- #
loss:
  NAME: SmoothCrossEntropy
  use_smoothing: True
  eps: 0.2

# ---------------------------------------------------------------------------- #
# Optimizer configs
# ---------------------------------------------------------------------------- #
optimizer:
  NAME: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 2.0e-4
  nesterov: True

# optimizer:
#   NAME: Adam
#   lr: 0.0005
#   betas: [0.9, 0.999]
#   weight_decay: 1.0e-4

# ---------------------------------------------------------------------------- #
# scheduler configs
# ---------------------------------------------------------------------------- #
# scheduler:
#   NAME: step
#   milestones: [140, 180]
#   gamma: 0.1

scheduler:
  NAME: cos
  eta_min: 5.0e-3
