# ---------------------------------------------------------------------------- #
# Task configs
# ---------------------------------------------------------------------------- #
epochs: 300
mode: train                   # [train, test]
grad_norm_clip: 1
# seed: 6

# ---------------------------------------------------------------------------- #
# Experimenet configs
# ---------------------------------------------------------------------------- #
experiment:
  exp_root_path: log/DifferentExpansion
  exp_name: ScanObjectNN_BLCurveNetCls
  save_file_list: ['main.py', 'build.py', 'datasets.py', 'losses.py', 'utils.py', 'models/BLCurveNetCls.py',
      'models/modules/point_utils.py', 'models/modules/model_utils.py', 'models/modules/expansion_utils.py']

# ---------------------------------------------------------------------------- #
# Dataset configs
# ---------------------------------------------------------------------------- #
dataset:
  common:
    NAME: ScanObjectNN
    data_path: data
    num_points: 1024
  train:
    split: train
  test:
    split: test

# ---------------------------------------------------------------------------- #
# Dataloader configs
# ---------------------------------------------------------------------------- #
dataloader:
  train:
    batch_size: 32
    num_workers: 8
  test:
    batch_size: 16
    num_workers: 8

# ---------------------------------------------------------------------------- #
# Model configs
# ---------------------------------------------------------------------------- #
model:
  NAME: BLCurveNetCls
  n_cls: 15
  k_g: 20

# ---------------------------------------------------------------------------- #
# Loss configs
# ---------------------------------------------------------------------------- #
loss:
  NAME: SmoothCrossEntropy
  use_smoothing: True
  eps: 0.2

# ---------------------------------------------------------------------------- #
# Optimizer configs
# ---------------------------------------------------------------------------- #
optimizer:
  NAME: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 1.0e-4
  nesterov: True

# optimizer:
#   NAME: Adam
#   lr: 0.0005
#   betas: [0.9, 0.999]
#   weight_decay: 1.0e-4

# ---------------------------------------------------------------------------- #
# scheduler configs
# ---------------------------------------------------------------------------- #
# scheduler:
#   NAME: step
#   milestones: [140, 180]
#   gamma: 0.1

scheduler:
  NAME: cos
  eta_min: 2.0e-3
